Added some additional unit testing of MergeGroup and ParallelMeshGen
Only two methods of ParallelMeshGen are tested, the rest are handled
with integration tests

diff --git a/test/fixtures/bin/mergeMeshes b/test/fixtures/bin/mergeMeshes
--- a/test/fixtures/bin/mergeMeshes
+++ b/test/fixtures/bin/mergeMeshes
@@ -2,3 +2,23 @@
 
 echo "mergeMeshes Dummy Executable"
 
+if [ ! $1 == '-overwrite' ]; then
+    echo "-overwrite flag was not the first argument"
+    exit 1
+fi
+
+if [ ! $2 ]; then
+    echo "no path to master case given"
+    exit 1
+fi
+
+if [ ! $3 ]; then
+    echo "no path to slave case given"
+    exit 1
+fi
+
+# adding statement to force a return code of 1
+if [ $(echo $3 | grep 'exit1') ]; then
+    echo "forced return code of 1"
+    exit 1
+fi
diff --git a/test/fixtures/bin/stitchMesh b/test/fixtures/bin/stitchMesh
--- a/test/fixtures/bin/stitchMesh
+++ b/test/fixtures/bin/stitchMesh
@@ -1,3 +1,34 @@
 #!/bin/bash
 
 echo "stitchMesh dummy executable"
+
+if [ ! $1 == '-case' ]; then
+    echo "-case arg is not the first argument"
+    exit 1
+fi
+
+if [ ! $3 == '-overwrite' ]; then
+    echo "-overwrite flag is not third argument"
+    exit 1
+fi
+
+if [ ! $4 == '-perfect' ]; then
+    echo "-perfect flag is not the fourth argument"
+    exit 1
+fi
+
+if [ ! $5 ]; then
+    echo "no master patch provided to stitch"
+    exit 1
+fi
+
+if [ ! $6 ]; then
+    echo "no slave patch provided to stitch"
+    exit 1
+fi
+
+# adding final statement to fore return code of 1
+if [ $(echo $6 | grep 'exit1') ]; then
+    echo 'Forced return code of 1'
+    exit 1
+fi
